---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: elk
  name: logstash-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash-ingest
  template:
    metadata:
      labels:
        app: logstash-ingest
    spec:
      containers:
        - name: logstash-ingest
          image: logstash:7.6.2
          volumeMounts:
            - name: logstash-ingest-conf
              mountPath: /usr/share/logstash/config
            - name: 'logstash-ingest-pipeline'
              mountPath: /usr/share/logstash/pipeline
            - name: 'logstash-ingest-logs'
              mountPath: /opt/logs
      volumes:
        - name: 'logstash-ingest-conf'
          hostPath:
            path: /home/sabbath/workspace-rancher/a-service/logstash/conf
        - name: 'logstash-ingest-pipeline'
          hostPath:
            path: /home/sabbath/workspace-rancher/a-service/logstash/pipeline
        - name: 'logstash-ingest-logs'
          hostPath:
            path: /home/sabbath/workspace-rancher/a-service/logs

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: logstash-ingest-service
#  namespace: elk
#spec:
#  selector:
#    app: logstash-ingest
#  ports:
#    - name: port1
#      port: 9200
#      targetPort: 9200
#    - name: port2
#      port: 9300
#      targetPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-ingest-nodeport
  namespace: elk
spec:
  type: NodePort
  selector:
    app: logstash-ingest
  ports:
    - port: 5046
      protocol: TCP
      nodePort: 30005




